# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    kernel.listener.logged_in_user_listener:
        class: notesBundle\Listener\LoggedInUserListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments:
            - "@security.token_storage"
            - "@router"

    notes.security.authentication_handler:
            class: notesBundle\Handler\AuthenticationHandler
            public: false
            arguments:
                - "@router"
                - "@session"